# Get the absolute root path of the repo
$RepoRoot = $PSScriptRoot

# 1. Build Boost
cd "$RepoRoot\boost"
.\bootstrap.bat
.\b2.exe link=static runtime-link=static threading=multi address-model=64 -a --layout=versioned stage

# 2. Build MPIR
cd "$RepoRoot\mpir\msvc\vs22"
.\msbuild.bat gc LIB x64 Release

# 3. Build MPFR (The problematic part)
cd "$RepoRoot\mpfr"
# Create the architecture folder if it's missing (needed for MPFR on modern systems)
if (-not (Test-Path "src\x86_64\corei5")) {
    New-Item -ItemType Directory -Force -Path "src\x86_64\corei5"
    Copy-Item -Path "src\x86_64\core2\*" -Destination "src\x86_64\corei5" -Recurse -Force
}

cd "$RepoRoot\mpfr\build.vs22\lib_mpfr"
msbuild /p:Configuration=Release /p:Platform=x64 lib_mpfr.vcxproj

# 3b. Patch MPIR's generated gmp.h to declare GMP version 6.1.2
# Ledger 3.4.1 requires GMP >= 6.1.2, but MPIR's gmp.h reports 6.0.0.
# MPIR is fully API-compatible with GMP 6.1.2; only the version marker needs patching.
$gmpSrc = "$RepoRoot\mpir\lib\x64\Release\gmp.h"
$gmpWrapDir = "$RepoRoot\gmp-include"
New-Item -ItemType Directory -Force -Path $gmpWrapDir | Out-Null
$gmpContent = Get-Content $gmpSrc -Raw
$gmpContent = $gmpContent -replace '(#define __GNU_MP_VERSION_MINOR\s+)0(?=\s|$)', '${1}1'
$gmpContent = $gmpContent -replace '(#define __GNU_MP_VERSION_PATCHLEVEL\s+)0(?=\s|$)', '${1}2'
Set-Content -Path "$gmpWrapDir\gmp.h" -Value $gmpContent -NoNewline
Write-Host "Patched gmp.h written to $gmpWrapDir\gmp.h"

# 3c. Locate the Boost cmake config directory generated by b2 stage
$boostCmakeDirs = @(Get-ChildItem "$RepoRoot\boost\stage\lib\cmake" -Filter "Boost-*" -Directory -ErrorAction SilentlyContinue)
if ($boostCmakeDirs.Count -eq 0) {
    Write-Error "Boost cmake config directory not found under boost\stage\lib\cmake. Ensure b2 stage completed successfully."
    exit 1
}
if ($boostCmakeDirs.Count -gt 1) {
    Write-Warning "Multiple Boost cmake config directories found; selecting the highest version."
}
$boostCmakeDir = ($boostCmakeDirs | Sort-Object Name -Descending | Select-Object -First 1).FullName
Write-Host "Found Boost cmake config at: $boostCmakeDir"

# 4. Build Ledger
cd "$RepoRoot\ledger"
cmake -G "Visual Studio 17 2022" -A x64 `
    -DCMAKE_BUILD_TYPE:STRING="Release" `
    -DUSE_PYTHON=OFF `
    -DBUILD_LIBRARY=OFF `
    -DBUILD_DOCS:BOOL="0" `
    -DHAVE_REALPATH:BOOL="0" `
    -DHAVE_GETPWUID:BOOL="0" `
    -DHAVE_GETPWNAM:BOOL="0" `
    -DHAVE_IOCTL:BOOL="0" `
    -DHAVE_ISATTY:BOOL="0" `
    -DMPFR_LIB:FILEPATH="$RepoRoot/mpfr/build.vs22/lib/x64/Release/mpfr.lib" `
    -DGMP_LIB:FILEPATH="$RepoRoot/mpir/lib/x64/Release/mpir.lib" `
    -DMPFR_PATH:PATH="$RepoRoot/mpfr/lib/x64/Release" `
    -DGMP_PATH:PATH="$gmpWrapDir" `
    -DBoost_DIR:PATH="$boostCmakeDir" `
    -DBoost_USE_STATIC_LIBS:BOOL="1" `
    -DCMAKE_CXX_FLAGS_RELEASE:STRING="/MT /Zi /Ob0 /Od"

msbuild /p:Configuration=Release /p:Platform=x64 src\ledger.vcxproj

# 5. Move output to root
Write-Host "--- Searching for ledger.exe in the entire repository ---"
# This finds the exe regardless of which 'Release' or 'bin' folder it landed in
$exePath = Get-ChildItem -Path "$RepoRoot" -Filter "ledger.exe" -Recurse -File | Select-Object -First 1 -ExpandProperty FullName

if ($exePath) {
    Write-Host "SUCCESS: Found ledger.exe at: $exePath"
    # Copy it to the root so the GitHub 'Upload' step can find it easily
    Copy-Item -Path "$exePath" -Destination "$RepoRoot\ledger.exe" -Force
    Write-Host "Staged ledger.exe to repository root."
} else {
    Write-Error "CRITICAL: Build reported success, but no ledger.exe was found anywhere in $RepoRoot"
    exit 1
}
